# Generated by Django 4.1.7 on 2025-01-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0006_alter_ingredient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
